---
# containerd
containerd_systemd_cgroup_driver:
  plugins:
    io.containerd.grpc.v1.cri:
      containerd:
        runtimes:
          runc:
            options:
              SystemdCgroup: true

# kubeadm
kube_version: 1.23.6
