---
# containerd
containerd_systemd_cgroup_driver:
  plugins:
    io.containerd.grpc.v1.cri:
      containerd:
        runtimes:
          runc:
            options:
              SystemdCgroup: true
controlplane_node_hostname: "{{ groups['controlplane'][0] }}"
controlplane_node_ip: "{{ hostvars[controlplane_node_hostname]['ansible_facts']['enp0s8']['ipv4']['address'] }}"
# kubeadm
kube_version: 1.23.6

kube_apiserver_port: 6443
kube_pod_network_cidr: 172.16.0.0/16

kubeadm_init_options:
  apiserver-advertise-address: "{{ controlplane_node_ip }}"
  control-plane-endpoint: "{{ controlplane_node_ip }}:{{ kube_apiserver_port }}"
  apiserver-cert-extra-sans: "{{ controlplane_node_ip }}"
  pod-network-cidr: "{{ kube_pod_network_cidr }}"

# prometheus
prometheus_namespace: prometheus
prometheus_kube_prometheus_stack: prometheus
prometheus_service: "{{ prometheus_kube_prometheus_stack }}-kube-prometheus-prometheus.{{ prometheus_namespace }}"
