- name: Template the containerd configuration
  become: yes
  template:
    src: tigera-operator/values.yaml
    dest: $HOME/tigera-operator-values.yaml
    mode: '0644'
    owner: root
    group: root

- name: Install Tigera operator release
  become: yes
  command: |
    helm upgrade --install \
      tigera-operator tigera-operator \
      -n tigera-operator --create-namespace \
      --repo https://projectcalico.docs.tigera.io/charts
      --values $HOME/tigera-operator-values.yaml

