- name: Create the module file for CRI-O
  become: yes
  file:
    state: touch
    path: /etc/modules-load.d/crio.conf
    access_time: preserve
    modification_time: preserve

- name: Configure CRI-O module
  become: yes
  blockinfile:
    insertafter: EOF
    path: /etc/modules-load.d/crio.conf
    block: |
      overlay
      br_netfilter

- name: Add modules overlay and br_netfilter
  become: yes
  command: "modprobe {{ item }}"
  with_items:
  - overlay
  - br_netfilter

- name: Setup required sysctl net params
  become: yes
  sysctl:
    state: present
    name: "net.{{ item }}"
    value: 1
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
  with_items:
  - bridge.bridge-nf-call-iptables
  - ipv4.ip_forward
  - bridge.bridge-nf-call-ip6tables

- name: Add repository keys for CRI-O
  become: yes
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
  - "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{ crio_version }}/{{ crio_os }}/Release.key"
  - "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ crio_os }}/Release.key"

- name: Add repositories for CRI-O
  become: yes
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ crio_os }}/ /"
  - "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ crio_version }}/{{ crio_os }}/ /"

- name: Install CRI-O
  become: yes
  apt:
    state: present
    update_cache: yes
    name:
    - cri-o
    - cri-o-runc

- name: Enable & Start CRI-O
  become: yes
  systemd:
    enabled: yes
    state: started
    name: crio
    daemon_reload: true

- name: Create the configurtaion for CRI-O capabilities
  become: yes
  file:
    state: touch
    path: /etc/crio/crio.conf.d/03-capabilities.conf
    access_time: preserve
    modification_time: preserve

- name: Configure default capabilities for CRI-O
  become: yes
  blockinfile:
    insertafter: EOF
    path: /etc/crio/crio.conf.d/03-capabilities.conf
    block: |
      [crio.runtime]
      default_capabilities = [
        "CHOWN",
        "DAC_OVERRIDE",
        "FSETID",
        "FOWNER",
        "SETGID",
        "SETUID",
        "SETPCAP",
        "NET_BIND_SERVICE",
        "KILL",
        "NET_RAW",
      ]

- name: Reload CRI-O
  become: yes
  systemd:
    state: reloaded
    name: crio
    daemon_reload: true
