- name: Add ingress-nginx chart repo
  become: yes
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx

- name: Install ingress-nginx release
  become: yes
  kubernetes.core.helm:
    name: ingress-nginx
    namespace: ingress-nginx
    create_namespace: true
    chart_ref: ingress-nginx/ingress-nginx
    update_repo_cache: true
