---
- import_tasks: swapoff.yaml
  tags:
  - kubernetes
  - kubernetes/swapoff

- import_tasks: cri.yaml
  tags:
  - kubernetes
  - kubernetes/cri

- import_tasks: bash_kubectl.yaml
  tags:
  - kubernetes
  - kubernetes/bash_kubectl

- import_tasks: kube_install.yaml
  tags:
  - kubernetes
  - kubernetes/kube_install

- import_tasks: kubeadm.yaml
  tags:
  - kubernetes
  - kubernetes/kubeadm

- import_tasks: calico.yaml
  tags:
  - kubernetes
  - kubernetes/calico
  when:
  - cni == 'calico'

- import_tasks: flannel.yaml
  tags:
  - kubernetes
  - kubernetes/flannel
  when:
  - "'controlplane' is in group_names"
  - cni == "flannel"

- import_tasks: helm.yaml
  tags:
  - kubernetes
  - kubernetes/helm
  when: "'controlplane' in group_names"

- import_tasks: metallb.yaml
  tags:
  - kubernetes
  - kubernetes/metallb
  when:
  - "'controlplane' is in group_names"

- import_tasks: ingress-nginx.yaml
  tags:
  - kubernetes
  - kubernetes/ingress-nginx
  when:
  - "'controlplane' is in group_names"

- import_tasks: storage_class.yaml
  tags:
  - kubernetes
  - kubernetes/storage_class
  when:
  - "'controlplane' in group_names"
  - storage_class

- import_tasks: metrics_server.yaml
  tags:
  - kubernetes
  - kubernetes/metrics_server
  when:
  - "'controlplane' in group_names"
  - metrics_server

- import_tasks: prometheus.yaml
  tags:
  - kubernetes
  - kubernetes/prometheus
  when:
  - "'controlplane' in group_names"
  - prometheus

- import_tasks: keda.yaml
  tags:
  - kubernetes
  - kubernetes/keda
  when:
  - "'controlplane' in group_names"
  - keda

- import_tasks: plugin.yaml
  tags:
  - kubernetes
  - kubernetes/plugin
  when:
  - "'controlplane' in group_names"
  - plugin
