---
- import_tasks: swapoff.yaml
  tags:
  - kubernetes/swapoff
- import_tasks: containerd.yaml
  tags:
  - kubernetes/containerd
- import_tasks: kube_install.yaml
  tags:
  - kubernetes/kube_install.yaml
