- name: Install MetalLB release
  become: yes
  command: helm upgrade --install metallb metallb -n metallb-system --create-namespace --repo https://metallb.github.io/metallb

- name: Create the directory for metallb
  become: yes
  file:
    state: directory
    path: $HOME/metallb

- name: Copy the l2conf.yaml
  become: yes
  copy:
    src: l2conf.yaml
    dest: $HOME/metallb/
    mode: '0644'

- name: Install l2conf
  become: yes
  command: kubectl apply -f $HOME/metallb/l2conf.yaml
