- name: Add metallb chart repo
  become: yes
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: https://metallb.github.io/metallb


- name: Install MetalLB release
  become: yes
  kubernetes.core.helm:
    name: metallb
    namespace: metallb-system
    create_namespace: true
    chart_ref: metallb/metallb
    update_repo_cache: true

- name: Create the directory for metallb
  become: yes
  file:
    state: directory
    path: $HOME/metallb

- name: Wait graceful period for installing metallb
  pause:
    seconds: 30

- name: Copy the l2conf.yaml
  become: yes
  copy:
    src: l2conf.yaml
    dest: $HOME/metallb/
    mode: '0644'

- name: Install l2conf
  become: yes
  command: kubectl apply -f $HOME/metallb/l2conf.yaml
