- name: Add Helm repository metrics-server
  become: yes
  kubernetes.core.helm_repository:
    name: metrics-server
    repo_url: https://kubernetes-sigs.github.io/metrics-server/

- name: Install Helm chart metrics-server
  become: yes
  kubernetes.core.helm:
    state: present
    name: metrics-server
    chart_ref: metrics-server/metrics-server
    release_namespace: kube-system
    values:
      nodeSelector:
        kubernetes.io/hostname: "{{ controlplane_node_hostname }}"
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
