- name: Add Helm repository metrics-server
  become: yes
  command: helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/

- name: Install Helm chart metrics-server
  become: yes
  command: helm upgrade --install metrics-server metrics-server/metrics-server -n kube-system
