- name: Download Krew
  become: yes
  unarchive:
    src: https://github.com/kubernetes-sigs/krew/releases/latest/download/krew-linux_amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Install Krew
  become: yes
  command: /tmp/krew-linux_amd64 install krew

- name: Delete Krew installation binary
  become: yes
  file:
    state: absent
    path: /tmp/krew-linux_amd64

- name: Add the Krew binary path to the PATH variable
  become: yes
  lineinfile:
    state: present
    insertafter: EOF
    path: $HOME/.bashrc
    line: export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

#- name: Install Krew plugins
#  become: yes
#  shell: "source $HOME/.bashrc && kubectl krew install {{ item }}"
#  args:
#    executable: /bin/bash
#  with_items:
#  - get-all
