- name: Local-path-storage
  become: yes
  block:
  - name: Download local-path-storage manifest file
    get_url:
      url: https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.22/deploy/local-path-storage.yaml
      dest: $HOME/local-path-storage.yaml
      mode: '0644'

  - name: Get the downloaded manifest file
    stat:
      path: $HOME/local-path-storage.yaml
    register: local_path_storage_file

  - name: Install local-path-provisioner
    kubernetes.core.k8s:
      state: present
      src: $HOME/local-path-storage.yaml
    when: local_path_storage_file.stat.exists

  - name: Get teh storage class local-path
    kubernetes.core.k8s_info:
      kind: StorageClass
      name: local-path
    register: storage_class_local_path

  - name: Set the default storage class as local-path
    kubernetes.core.k8s:
      state: patched
      kind: StorageClass
      name: local-path
      definition:
        metadata:
          annotations:
            storageclass.kubernetes.io/is-default-class: "true"
    when: storage_class_local_path.resources | length > 0

- name: Nfs-provisioner
  become: yes
  block:
  - name: Add Helm repository nfs-subdir-external-provisioner
    kubernetes.core.helm_repository:
      state: present
      name: nfs-subdir-external-provisioner
      repo_url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner

  - name: Install Helm chart nfs-provisioner
    kubernetes.core.helm:
      name: nfs-provisioner
      namespace: nfs-provisioner
      chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
      create_namespace: yes
      values:
        nfs:
          path: /nfs-storage
          server: "{{ controlplane_node_ip }}"
          nodeSelector:
          kubernetes.io/hostname: "{{ controlplane_node_hostname }}"
        tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule

