---
- name: Add mapping to /etc/hosts
  become: yes
  blockinfile:
    path: /etc/hosts
    block: |
      192.168.1.2 node-1
      192.168.1.3 node-2
      192.168.1.4 node-3
      192.168.1.5 node-4

